### ISSUE TITLE
Make setup.py work

### ISSUE THREAD

**Issue by hanss314** [hanss314/PyDanmaku#3]
There was a large overhaul of the engine so setup.py almost definitely doesn't work. It needs to create an extension out of all the .cpp files in `pydanmaku` named `pydanmaku.so` and install it to the `site-packages` folder (as most setup.py do). Any .py files are irrelevant to the package and are either legacy code or for testing.

**Comment by yurrr** [comment]
Can you point me to where start to solve this ?

**Comment by hanss314** [comment]
[Docs for a setup.py](https://docs.python.org/3/distutils/setupscript.html)

**Comment by qixils** [comment]
Wasn't this fixed with #7?
